#!/usr/bin/env bash
# Makes the game run by itself: start at boot, restart if it crashes, update
# itself, and back itself up nightly.
#
#   ./scripts/install-services.sh
#
# Run it once. Safe to run again - it overwrites its own files and does not
# duplicate crontab entries.
#
# After this you no longer need terminal windows open. The game survives
# reboots, and new versions land on their own.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_USER="${SUDO_USER:-$USER}"

say()  { printf '\n\033[1;36m>> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m   %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ------------------------------------------------------------------ checks ---
command -v systemctl >/dev/null 2>&1 || die "systemd is not available."
systemctl list-units >/dev/null 2>&1 || die \
"systemd is present but not running.
   On WSL2 you need to turn it on first:

     sudo tee /etc/wsl.conf > /dev/null <<'EOF'
     [boot]
     systemd=true
     EOF

   Then, in PowerShell:  wsl --shutdown
   Reopen Ubuntu and run this again."

[[ -x "$REPO_ROOT/scripts/run-web.sh" ]] || die "run-web.sh missing - wrong directory?"
[[ -f "$REPO_ROOT/.env" ]] || die ".env not found. Run ./scripts/setup.sh first."

# systemd reads EnvironmentFile itself and does not run a shell, so it cannot
# expand $HOME or handle the layered .env + game-settings.env that the scripts
# use. Passing the repo path in and letting the scripts source both keeps one
# source of truth.
say "Installing services for user '$RUN_USER', repo at $REPO_ROOT"

install_unit() {
  local name="$1" desc="$2" exec="$3"
  sudo tee "/etc/systemd/system/$name.service" > /dev/null <<EOF
# Generated by scripts/install-services.sh - re-run that rather than editing.
[Unit]
Description=$desc
After=network-online.target mariadb.service mysql.service
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$REPO_ROOT
ExecStart=$exec
Restart=always
RestartSec=15
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
  echo "   wrote /etc/systemd/system/$name.service"
}

install_unit airline-sim "Airline Club background simulation (the game clock)" \
             "$REPO_ROOT/scripts/run-simulation.sh"
install_unit airline-web "Airline Club web site" \
             "$REPO_ROOT/scripts/run-web.sh"

# ---------------------------------------------------------------- sudo rule ---
# update.sh restarts the services, and auto-update runs unattended from cron
# where nobody can type a password. Grant exactly those two commands, nothing
# more.
say "Allowing '$RUN_USER' to restart just these two services without a password"
sudo tee /etc/sudoers.d/airline-club > /dev/null <<EOF
# Generated by scripts/install-services.sh
$RUN_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart airline-web, /usr/bin/systemctl restart airline-sim, /usr/bin/systemctl stop airline-web, /usr/bin/systemctl stop airline-sim, /usr/bin/systemctl start airline-web, /usr/bin/systemctl start airline-sim
EOF
sudo chmod 440 /etc/sudoers.d/airline-club
sudo visudo -c -f /etc/sudoers.d/airline-club >/dev/null \
  || die "the sudoers rule is malformed - removing it: sudo rm /etc/sudoers.d/airline-club"

# ------------------------------------------------------------------- start ---
say "Starting them"
sudo systemctl daemon-reload
sudo systemctl enable --now airline-sim airline-web

# ------------------------------------------------------------------- cron ----
say "Scheduling automatic updates and nightly backups"
CRON_UPDATE="*/10 * * * * cd $REPO_ROOT && ./scripts/auto-update.sh >> $REPO_ROOT/backups/auto-update.log 2>&1"
CRON_BACKUP="0 4 * * * cd $REPO_ROOT && ./scripts/backup-db.sh >> $REPO_ROOT/backups/backup.log 2>&1"

mkdir -p "$REPO_ROOT/backups"
# Drop any previous lines of ours before adding, so re-running does not stack.
( crontab -l 2>/dev/null | grep -v 'airline.*scripts/\(auto-update\|backup-db\).sh' || true
  echo "$CRON_UPDATE"
  echo "$CRON_BACKUP" ) | crontab -
echo "   every 10 minutes: check for updates (does nothing when there are none)"
echo "   every night at 4am: back up the database"

# ------------------------------------------------------------------ report ---
say "Done"
sleep 3
systemctl --no-pager --lines=0 status airline-sim airline-web 2>/dev/null \
  | grep -E "^.\s+airline|Active:" || true

cat <<EOF

   The game now:
     - starts by itself when Linux starts
     - restarts by itself if it crashes
     - updates itself within 10 minutes of a new version
     - backs itself up every night at 4am

   Useful commands:
     systemctl status airline-web airline-sim     are they alive?
     journalctl -u airline-sim -f                 watch the game clock
     journalctl -u airline-web -f                 watch the web site
     ./scripts/game-time.sh                       where the game is

   To pause automatic updates without touching cron, set
   AIRLINE_AUTO_UPDATE=off in game-settings.env.

EOF

if ! grep -q "systemd=true" /etc/wsl.conf 2>/dev/null; then
  warn "Note: /etc/wsl.conf does not enable systemd, so this may not survive a"
  warn "reboot. See 'start on its own' in WINDOWS-SETUP.md."
fi

echo "   One last thing, on Windows: make Linux itself start at boot, or none"
echo "   of the above runs until you open the Ubuntu window. In PowerShell as"
echo "   Administrator:"
echo
echo '     $a = New-ScheduledTaskAction -Execute "wsl.exe" -Argument "-d Ubuntu -- exit"'
echo '     $t = New-ScheduledTaskTrigger -AtStartup'
echo '     Register-ScheduledTask -TaskName "Start WSL Airline" -Action $a -Trigger $t -RunLevel Highest -User "SYSTEM"'
echo
