#!/usr/bin/env bash
# One-shot installer for a fresh Ubuntu (including WSL2 on Windows).
#
#   ./scripts/setup.sh
#
# Installs Java and MariaDB, configures the database correctly, generates
# passwords, builds the game and loads the world. Everything the manual
# instructions do, minus the typing.
#
# Safe to re-run: it skips anything already done and never overwrites an
# existing .env or an existing world without asking.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SCHEMA="${AIRLINE_DB_SCHEMA:-airline_v2_1}"
DB_USER="${AIRLINE_DB_USER:-sa}"

say()  { printf '\n\033[1;36m>> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m   %s\033[0m\n' "$*"; }
die()  { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- checks ---
[[ "$(uname -s)" == "Linux" ]] || die "This installer is for Linux. On Windows, run it inside WSL2 (open the Ubuntu app)."
[[ $EUID -ne 0 ]] || warn "Running as root. That works, but a normal user with sudo is tidier."

if [[ "$PWD" == /mnt/* ]]; then
  warn "You are on the Windows side of the filesystem ($PWD)."
  warn "This will be VERY slow - the setup reads ~85MB of data files."
  warn "Recommended: move the repo into your Linux home, e.g. ~/airline"
  read -r -p "   Continue anyway? [y/N] " a
  [[ "$a" == "y" || "$a" == "Y" ]] || exit 1
fi

command -v sudo >/dev/null 2>&1 || die "sudo is not installed."

# ------------------------------------------------------------- packages ---
say "Installing Java, MariaDB and tools (this needs your password)"
# A broken third-party repository must not abort the whole install - the
# packages we need live in the main Ubuntu archive, so carry on and let the
# install step below be the thing that fails if they are genuinely missing.
if ! sudo apt-get update -qq 2>/tmp/apt-update-err; then
  warn "Some package sources failed to refresh (probably an unrelated PPA):"
  grep -oE "https?://[^ ]+" /tmp/apt-update-err | sort -u | sed 's/^/     /' | head -4
  warn "Continuing - the packages needed here come from the main Ubuntu archive."
fi

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  openjdk-21-jdk mariadb-server mariadb-client git openssl >/dev/null \
  || die "Could not install the required packages. Check your internet connection and run: sudo apt-get install openjdk-21-jdk mariadb-server git"
echo "   java: $(java -version 2>&1 | head -1)"

# ------------------------------------------------------------- database ---
say "Configuring MariaDB"
# utf8mb4 is mandatory: without it the world import dies on the first city
# name with an accent or non-Latin characters.
#
# The directory only exists once mariadb-server is installed, which is why
# this runs after apt and not before. Create it anyway so a partial install
# gives a clear failure later rather than "No such file or directory" here.
sudo mkdir -p /etc/mysql/mariadb.conf.d
sudo tee /etc/mysql/mariadb.conf.d/99-airline.cnf > /dev/null <<'EOF'
[mysqld]
character_set_server = utf8mb4
collation_server = utf8mb4_general_ci
bind-address = 127.0.0.1
max_connections = 300
innodb_buffer_pool_size = 2G
innodb_flush_log_at_trx_commit = 2
EOF

if command -v systemctl >/dev/null 2>&1 && systemctl list-units >/dev/null 2>&1; then
  sudo systemctl enable --now mariadb >/dev/null 2>&1 || true
  sudo systemctl restart mariadb
else
  warn "No systemd - starting MariaDB directly."
  warn "Turn systemd on so it starts at boot: see WINDOWS-SETUP.md step 2."
  sudo mkdir -p /var/run/mysqld && sudo chown mysql:mysql /var/run/mysqld
  pgrep -x mariadbd >/dev/null || sudo setsid nohup mariadbd --user=mysql >/tmp/mariadb.log 2>&1 < /dev/null &
fi

for _ in $(seq 1 45); do sudo mariadb -e "SELECT 1" >/dev/null 2>&1 && break; sleep 2; done
sudo mariadb -e "SELECT 1" >/dev/null 2>&1 || die "MariaDB did not come up. Check: sudo journalctl -u mariadb -n 50"
echo "   MariaDB is up."

# ----------------------------------------------------------------- .env ---
if [[ -f .env ]]; then
  say "Keeping your existing .env"
  # shellcheck disable=SC1091
  DB_PASS="$(grep -E '^AIRLINE_DB_PASSWORD=' .env | cut -d= -f2- | tr -d '"'"'"'' || true)"
  [[ -n "$DB_PASS" ]] || die "AIRLINE_DB_PASSWORD is missing from .env - fix it or delete .env and re-run."
else
  say "Generating passwords and writing .env"
  DB_PASS="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
  APP_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  cat > .env <<EOF
# Generated by scripts/setup.sh - keep this file private, it is not in git.
AIRLINE_DB_HOST=localhost:3306
AIRLINE_DB_SCHEMA=$SCHEMA
AIRLINE_DB_USER=$DB_USER
AIRLINE_DB_PASSWORD=$DB_PASS
AIRLINE_APP_SECRET=$APP_SECRET
EOF
  chmod 600 .env
  echo "   Wrote .env (passwords generated for you)."
fi

say "Creating the database and its user"
sudo mariadb <<EOF
CREATE DATABASE IF NOT EXISTS \`$SCHEMA\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
ALTER USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON \`$SCHEMA\`.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;
EOF
echo "   Database '$SCHEMA' ready."

# ---------------------------------------------------------------- build ---
say "Building the game (a few minutes - it downloads the libraries)"
./scripts/build.sh

# ----------------------------------------------------------------- world ---
EXISTING=$(mariadb --user="$DB_USER" --password="$DB_PASS" --skip-column-names --batch \
  -e "SELECT COUNT(*) FROM user;" "$SCHEMA" 2>/dev/null || echo "")

if [[ -n "$EXISTING" && "$EXISTING" -gt 0 ]]; then
  say "World already loaded, and $EXISTING player(s) are registered - leaving it alone"
  warn "Re-running the world import would delete them. Use ./scripts/init-database.sh if you really mean to."
else
  say "Loading the world - airports, cities, runways (5-10 minutes, be patient)"
  ./scripts/init-database.sh
fi

# ----------------------------------------------------------------- done ---
say "Done."
cat <<'EOF'

   Start the game with two commands, in two separate terminals:

     ./scripts/run-simulation.sh     (the game clock - leave it running)
     ./scripts/run-web.sh            (the web site)

   Then open   http://localhost:9000   and click Sign Up.

   Next steps, when that works:
     - let friends in       ->  see "Tailscale" in WINDOWS-SETUP.md
     - start it at boot     ->  see "start on its own" in WINDOWS-SETUP.md
     - change the pace      ->  edit game-settings.env

EOF
